name: 'Build ESP IDF project'

on:
  # Trigger the workflow on push only for the master branch
  push:
    branches:
      [ $default-branch ]
      
jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - run: ./build-ci.sh
