name: 'Build ESP IDF project'

on:
  # Trigger the workflow on push only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
      
      - name: Run the build action
        uses: ./.github/actions/build
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            build/blink.bin
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            
  unit-test:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
        
      - name: Unit testing
        run: make -f Makefile.unit_tests
